version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - "local-dev"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  redis:
    command: redis-server
    image: redis
    ports:
      - "6379:6379"
    networks:
      - "local-dev"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: limoneno
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - "local-dev"

networks:
  local-dev:
    external: false